### ISSUE TITLE
Who is the funder?

### ISSUE THREAD

**Issue by padilla410** [padilla410/lake-temp-mo-data-release#2]
https://github.com/padilla410/lake-temp-mo-data-release/blob/2ff309268ac46bf135484b9b778fa0c5bd0a2e27/in_text/text_data_release.yml#L125

**Comment by lindsayplatt** [comment]
I added funders based on the proposal documents available in our Sharepoint folders, but I think the phrasing should be checked by Jordan Read. PR coming soon and I will tag him.
